### ISSUE TITLE
oturum kontrolü

### ISSUE THREAD

**Issue by tekinnnnn** [tekinaydogdu/proje#20]
oturum açma yapmışız ama oturum kontrolü yapmamışız sanırım. onu yapmamız lazım. oturum açıksa ve session yoksa sadece cookie varsa cookie deki verileri session a da yükleyen bir fonksiyon yapmamız gerek.

bir de oturum aç ta cookie ye rol ü atarken yine veritabanından çekmişiz. üst satırda session da hazır çekilmişi var. fazladan sorguya gerek yok.

ayrıca biz adamın kullanıcı id sini cookie ye atıyoruz ve adam bunu görebilir. bence cookie de atıyorum oturum adında bir tek cookie oluşturup diğer verilerin hepsini ona array olarak atmalıyız ki adam kendi kullanıcı id sini veya taşıdığımız başka değerleri göremesin.

bi de hatırla diye bir cookie oluşturmamıza gerek kalmaz böyle yaparsak direk array imiz var mı cookie de diye bakarız. varsa true döner hatırla kontrol fonksiyonumuz. zaten diğer durumda da gerek olmaz. kul id sine baksak ta şu an eğer sitede verileri varsa hatırlıyor olur :)

**Comment by serong** [comment]
Oturum kontrolü yaptik diye hatırlıyorum. Login sayfasina gelince cookie varsa, session açıyor ve admin e yönlendiriyor. Derse gelince bakariz.

**Comment by serong** [comment]
Bir de Cookie de rol atarken veritabanından cekmek lazım. Cunku ustte haziri yok aslinda. if($hatirla) Session yokken de cagiriliyor.

**Comment by serong** [comment]
Yok yok, anladim şimdi ne dediğini. :)

**Comment by serong** [comment]
cookie'yi falan hallettik. Kapatıyorum o zaman bunu.
