### ISSUE TITLE
Mail Gönderimi

### ISSUE THREAD

**Issue by physicistt** [tekinaydogdu/proje#29]
fmail İle ilgili sıkıntı var sanırım dosyayı bilgisayara indirdim ama mail gönderemiyorum database ve şifre değişikliklerinide yaptım bide bu issue neymiş diye yazıyorum şu an bunu :)

**Comment by serong** [comment]
Hangi işlem sırasında sorun oldu Emre? Bu aktivasyon mail'i mi?

**Comment by physicistt** [comment]
aynen mailime gelmedi sizde bir tekrar denermisiniz ben birşeyi atlıyorum heralde

**Comment by serong** [comment]
Evdeki veritabanında kullanıcılar tablosunda mail'in var di mi? :) Yani kendin için mail'inin falan olduğu bir kullanıcı oluşturmuştun di mi? Fonksiyon kullanıcılar tablosunda mail var mı diye kontrol ediyor önce, varsa mail atıyor.

**Comment by physicistt** [comment]
evet yasinin maili vardı onu kendiminkiyle değiştirdim bir de şifreyi ekledim başka bir işlem gerekir mi?

**Comment by serong** [comment]
Aklıma gelen bir şey yok başka yapılacaklar arasında. Sadece bulutMail sınıfında şifre kısmını dolduruyorsun. O kadar. 

Bir hata veriyor mu?

Bir de kullanicilar_sifre_reset e ekleme yapıyor mu?

**Comment by physicistt** [comment]
tamam halloldu eyvallah :)
