### ISSUE TITLE
oturumu kapat işlevi

### ISSUE THREAD

**Issue by tekinnnnn** [tekinaydogdu/proje#39]
abi şunu da ekleyelim çabucak ya. bi defa oturum açıyorum kapanmıyor sonra namussuz :) benim chrome da çoklu sekme olayı açık olduğu için cookie leri de session ları da silmiyo bazen

**Comment by serong** [comment]
Süper Admin'de var, ama Şirket Admin henüz yok. Ekleriz onu da.
