### ISSUE TITLE
fonksiyonlara logo tam path'i alacak bir fonksiyon lazım.

### ISSUE THREAD

**Issue by serong** [tekinaydogdu/proje#41]

**Comment by tekinnnnn** [comment]
ben hallederim onu

**Comment by tekinnnnn** [comment]
1-veritabanına upload edilmek istenen dosyanın uzantısını atıyoruz bu hata giderilecek
2-şirket için sample logolar hazırlıyor merve. şirket kayıt edilirken bunlardan random bir tane seçilip onu kaydedelim. bu sayede logo upload yapan fonksiyonumuz karışmaz. çünkü orada update olarak yaptım.

**Comment by serong** [comment]
Kayıt işlemi gerçekleşirken o rastgele olanları atarız.

**Comment by tekinnnnn** [comment]
evet. ben de onu söylüyorum. son güncellemelere baktım da kayıt fonksiyonundan logo çıkmış sanırım. o kalsın yani..

**Comment by murataktas** [comment]
evet çıkardım kayıt kısmında logo eklemeyi


13 Nisan 2015 12:56 tarihinde Tekin Aydoğdu <notifications@github.com>
yazdı:

**Comment by serong** [comment]
Bence birden fazla logoya gerek yok. Direkt bir tane yapalım. Default o gelsin. Birden fazla gereksiz aksiyon.

**Comment by tekinnnnn** [comment]
mervede zaten görev yok ki abi başka. yaparım dedi de zaten

**Comment by serong** [comment]
İşte bir tane yeterli gibi değil mi? Birden fazla anlamsız geliyor bana.

**Comment by tekinnnnn** [comment]
Veritabanına uzantısız atalım onu. Fonksiyonla .jpg i koyalım bence. Madem alırken parçalayan fonksiyon yapıcaz, hiç uğraşmayalım parçalamakla. Direk o fonksiyon sadece jpg ini versin boyutunu versin..

**Comment by serong** [comment]
Olur. Ama ileride upload sınıfını degistirirsek (olur da birbsebep cikti) baska uzantili kaydedersek falan, bu sefer veritabaninda farkli uzantili şeyler koymak gerekirse isler biraz karışır. 

En iyisi ilk dedigin gibi veritabanına uzanti ile atıp fonksiyon ile cozmek sanki. Veritabaninda direkt yolu olsun. Boylece gelecek degisikliklere karsi daha guvende oluruz. :) 

Parcalamaya da gerek yok, strrev (stringi ters ceviriyor) ve strreplace beraber halledilir o.

**Comment by serong** [comment]
Fonksiyon tamamdır. **Bulut::logoGetir()**

Veritabanından uzantısı ile alıyor. Duruma göre id ile işlem yapabiliyorsun veya direkt dosya yolunu verip. Böylece daha önce SQL sorgusu ile gelmişse tekrar sorgu yapmaya gerek kalmıyor.
